version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: kenza
      MYSQL_DATABASE: game_react
      MYSQL_USER: kenza
      MYSQL_PASSWORD: kenza
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network: